spring:
  application:
    name: stream-transcoder-service

  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:db-registration}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

    # Configuration HikariCP
    hikari:
      maximum-pool-size: ${DB_POOL_MAX_SIZE:20}
      minimum-idle: ${DB_POOL_MIN_IDLE:5}
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  cloud:
    aws:
      region:
        static: ${AWS_REGION:us-east-1}

      sqs:
        queue-name: ${TRANSCODE_QUEUE_NAME:video-streaming-cluster-transcode-queue}
        listener:
          max-messages-per-poll: 1


aws:
  s3:
    bucket: ${AWS_S3_BUCKET:states3bucket-deploy}


transcode:
  queue:
    name: ${TRANSCODE_QUEUE_NAME:video-streaming-cluster-transcode-queue}

  hls:
    segment-duration-seconds: ${HLS_SEGMENT_DURATION:6}

  temp-dir: ${TRANSCODE_TEMP_DIR:/tmp/transcode}


logging:
  level:
    com.stream.transcoder: DEBUG
    io.awspring.cloud.sqs: DEBUG
    software.amazon.awssdk.services.sqs: DEBUG
    org.springframework.cloud.aws: INFO
